### ISSUE TITLE
Can't find the submenu

### ISSUE THREAD

**Issue by khalidelmerrah** [matheus-delazeri/magento-export#2]
Hello, Magento newbie here.

i installed the script and everything but i can't find the submenu, is there something i should run ? cache i should delete or something ? maybe activating the plugin like we do on wordpress. 

thanks

**Comment by matheus-delazeri** [comment]
Hey! Yes, you should flush the cache storage and the magento cache after installing it. After that, the submenu "Export Products" should be displayed in the "Catalog" menu.

If this don't work, check if the module is enabled in System -> Configuration -> Advanced (the module is named "Matheus_Export"). 

Let me know if it worked 😄

**Comment by khalidelmerrah** [comment]
@matheus-delazeri it works man thanks a lot 😄
